# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstagramFirestore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstagramFirestore
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Firebase/Messaging'
	pod 'Firebase/Auth'
	pod 'ActiveLabel'
	pod 'SDWebImage'
	pod 'JGProgressHUD'
	pod 'YPImagePicker'

  target 'InstagramFirestoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstagramFirestoreUITests' do
    # Pods for testing
  end

end
